import type { Metadata } from "next";
import {Spline_Sans_Mono } from "next/font/google"; 
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const splineSansMono = Spline_Sans_Mono({
  variable: "--font-spline-sans-mono",
  weight: ["700"],
});

export const metadata: Metadata = {
  title: "gym app",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${splineSansMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}